In [1]:
import torch
from torch import nn

In [6]:
model = nn.Linear(10, 1)

In [7]:
from Muon_pytorch import Muon

In [8]:
opt = Muon(model.parameters(), lr = 1e-4)

In [9]:
for _ in range(100):
    loss = model(torch.randn(10))
    print(loss)
    loss.backward()

    opt.step()
    opt.zero_grad()

tensor([-0.1054], grad_fn=<AddBackward0>)
tensor([-0.3494], grad_fn=<AddBackward0>)
tensor([-0.7432], grad_fn=<AddBackward0>)
tensor([-1.1249], grad_fn=<AddBackward0>)
tensor([1.0244], grad_fn=<AddBackward0>)
tensor([-0.2254], grad_fn=<AddBackward0>)
tensor([-0.4954], grad_fn=<AddBackward0>)
tensor([0.9162], grad_fn=<AddBackward0>)
tensor([-0.9662], grad_fn=<AddBackward0>)
tensor([0.1606], grad_fn=<AddBackward0>)
tensor([1.0418], grad_fn=<AddBackward0>)
tensor([-0.2938], grad_fn=<AddBackward0>)
tensor([-0.8955], grad_fn=<AddBackward0>)
tensor([-0.5005], grad_fn=<AddBackward0>)
tensor([-1.1482], grad_fn=<AddBackward0>)
tensor([0.2996], grad_fn=<AddBackward0>)
tensor([0.3303], grad_fn=<AddBackward0>)
tensor([-0.3352], grad_fn=<AddBackward0>)
tensor([1.0392], grad_fn=<AddBackward0>)
tensor([1.1593], grad_fn=<AddBackward0>)
tensor([0.6625], grad_fn=<AddBackward0>)
tensor([-0.0732], grad_fn=<AddBackward0>)
tensor([0.0850], grad_fn=<AddBackward0>)
tensor([-0.4864], grad_fn=<AddBackward0>)
te